Update Discord links
regen-network/regen-web pull request #2271
Opened 2024-01-26 02:20 UTC by brokenthumbs

## Description

Reference: https://discord.com/channels/684494798358315010/947551295546462278/1200253124137455709

- The Discord link in the footer currently leads to a compromised Discord server.
  - If you check the Discord at https://discord.gg/regen-network, you will find a phishing verification bot.
  - This is a problem for anybody who is not savvy enough to spot a phishing attempt.
- This PR updates the link to the actual Discord, which is referenced here: https://guides.regen.network/guides/regen-network/network-basics/connect-with-us
- Is there anything that can be done to delete or terminate the compromised Discord server at https://discord.gg/regen-network ?
  - Please strongly consider how to terminate the old compromised Discord server at https://discord.gg/regen-network

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1. Confirm that there is indeed a phishing verification bot in the current footer Discord link at https://discord.gg/regen-network
2. Confirm that the new Discord link, https://discord.gg/TbRfsNQGWH, leads to the actual Regen Discord server, as referenced by https://guides.regen.network/guides/regen-network/network-basics/connect-with-us

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

2024-01-30 10:43 UTC, blushi approved these changes
Thanks for your contribution!
We've reached to discord regarding the wrong regen-network server.
Pre-approving. Could you rebase your work on dev?

2024-01-30 19:48 UTC, clevinson requested changes
Thanks for the report and updating this!

The invite link in this PR currently directs people to the #activity-log, and I think it'd actually be better to direct people to the #welcome channel first.  I've just created a new invite link and suggested you update it here:

https://discord.gg/6ghMcMBjbz

2024-01-30 19:48 UTC, clevinson commented on web-components/src/components/footer/SocialLinks.tsx
> +          href="https://discord.gg/TbRfsNQGWH"
```suggestion
          href="https://discord.gg/6ghMcMBjbz"
```

2024-01-30 19:48 UTC, clevinson commented on web-www/components/templates/press-kit/ConnectSection/ConnectSection.config.tsx
> +    href: 'https://discord.gg/TbRfsNQGWH',
```suggestion
    href: 'https://discord.gg/6ghMcMBjbz',
```

2024-01-30 19:48 UTC, clevinson commented on web-www/components/templates/token/TokenConnectSection/TokenConnectSection.config.tsx
> +    href: 'https://discord.gg/TbRfsNQGWH',
```suggestion
    href: 'https://discord.gg/6ghMcMBjbz',
```

2024-01-30 20:30 UTC, brokenthumbs commented
Updated Discord link in pull request!

@clevinson You may also want to update the Discord link here as well: https://guides.regen.network/guides/regen-network/network-basics/connect-with-us

I don't know where that source code is for that particular FAQ page is.

2024-01-30 20:31 UTC, brokenthumbs commented
On another note, how did somebody take over that `discord.gg/regen-network` shortcut link?

2024-01-30 20:50 UTC, dpdanpittman commented
I would also like to know this. It seems like that shouldn't be possible.

On Tue, Jan 30, 2024, 1:32 PM Dan Chan ***@***.***> wrote:

> On another note, how did somebody take over that discord.gg/regen-network
> shortcut link?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/regen-network/regen-web/pull/2271#issuecomment-1917840939>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACBIMSUHREF6YF46HM37JFDYRFKEPAVCNFSM6AAAAABCLPQZ2SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMJXHA2DAOJTHE>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-01-31 01:19 UTC, clevinson approved these changes

2024-01-31 01:20 UTC, clevinson commented
@brokenthumbs @dpdanpittman I'm pretty sure that we just stopped paying for the feature (discord charges for you to have custom invite links) and forgot to change it on our website.  Then after a while, a hacker just created a new discord server and squatted / paid for the custom URL that we had used in the past.

2024-01-31 01:28 UTC, dpdanpittman commented
That makes sense.

On Tue, Jan 30, 2024, 6:20 PM Cory ***@***.***> wrote:

> @brokenthumbs <https://github.com/brokenthumbs> @dpdanpittman
> <https://github.com/dpdanpittman> I'm pretty sure that we just stopped
> paying for the feature (discord charges for you to have custom invite
> links) and forgot to change it on our website. Then after a while, a hacker
> just created a new discord server and squatted / paid for the custom URL
> that we had used in the past.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/regen-network/regen-web/pull/2271#issuecomment-1918190823>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACBIMSQN4U4AXCBVRDJB72TYRGL6TAVCNFSM6AAAAABCLPQZ2SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMJYGE4TAOBSGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-01-31 05:00 UTC, brokenthumbs commented
How long does the build take?
Thanks for approving!

Hope we can take down the bad actor Discord.
Or at least not send people there.

2024-02-08 09:02 UTC, merged