feat: buy credits step2
regen-network/regen-web pull request #2480
Opened 2024-09-23 15:50 UTC by blushi

## Description

- Step 2 (payment/customer info) and if entering new credit card, getting stripe confirmation token id as described in https://whimsical.com/stripe-flow-T4gUusQXghnWjobKbAd3Ex
- Getting initial values from local storage on both ChooseCreditsForm and PaymentsInfoForm which involved a bit of refactoring

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

2024-09-24 10:07 UTC, r41ph requested changes

2024-09-25 09:06 UTC, blushi commented on web-marketplace/src/hooks/useStorage.ts
> +  useLocalStorage: boolean,
renamed to `withLocalStorage` WDYT?

2024-09-25 16:00 UTC, r41ph commented on web-marketplace/src/hooks/useStorage.ts
> +  useLocalStorage: boolean,
Sounds good, thanks

2024-09-25 16:01 UTC, r41ph approved these changes

2024-09-26 08:05 UTC, merged