feat: APP-368 update /profile routes to be under /dashboard and /dashboard/admin
regen-network/regen-web pull request #2505
Opened 2024-10-16 16:09 UTC by r41ph

## Description

https://regennetwork.atlassian.net/browse/APP-375

### Author Checklist

- [x] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

2024-10-16 16:16 UTC, r41ph commented
@erikalogie see testing instructions

2024-10-16 20:27 UTC, erikalogie commented
LGTM

2024-10-23 08:30 UTC, blushi commented
could you update this branch to dev and make necessary changes for the stuff that has been added as part of https://github.com/regen-network/regen-web/pull/2486/files?

2024-10-23 10:42 UTC, blushi requested changes
Looks like we're missing a few existing links to `/profile` still:
`useOnProfileClick`
`ProfileEdit.Main`
`ProfileEdit.ViewProfile`

2024-10-23 10:43 UTC, blushi commented on web-marketplace/src/pages/Dashboard/Dashboard.constants.tsx
> +  href: '/dashboard/admin/settings',
Also the href should be updated for `MY_ORDERS, `MY_PREFINANCE_PROJECTS`, `SAVED_PAYMENT_INFO` below

2024-10-28 07:01 UTC, blushi approved these changes

2024-10-29 16:25 UTC, merged