fix: APP-394 disable the cursor pointer on hover steps
regen-network/regen-web pull request #2538
Opened 2024-11-11 10:28 UTC by r41ph

## Description

https://regennetwork.atlassian.net/browse/APP-394

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

2024-11-11 10:35 UTC, r41ph commented
@erikalogie see testing instructions

2024-11-11 12:52 UTC, erikalogie commented
LGTM

2024-11-12 08:47 UTC, blushi requested changes

2024-11-12 08:47 UTC, blushi commented on web-components/src/components/stepper/index.tsx
> +                  'hover:cursor-default',
this is overwritting the line above `onStepClick && styles.hover` 
I believe a better solution would be to have `onStepClick` not set at all for now in `StepperSection`

2024-11-12 12:51 UTC, blushi approved these changes

2024-11-13 14:59 UTC, merged